# Generated by Django 5.2.7 on 2026-04-06 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('planner', '0001_initial'),
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_record', to='assessments.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudySessionCompletion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('actual_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('completion_status', models.CharField(default='planned', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('study_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_record', to='planner.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_session_completion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_assessments', models.PositiveIntegerField(default=0)),
                ('completed_assessments', models.PositiveIntegerField(default=0)),
                ('total_planned_minutes', models.PositiveIntegerField(default=0)),
                ('total_completed_minutes', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress_record', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
