# Generated by Django 5.2.7 on 2026-04-06 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_study_end_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_study_start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
