# Generated by Django 5.2.7 on 2026-04-06 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('assessment_type', models.CharField(choices=[('assignment', 'Assignment'), ('cat', 'CAT'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('project', 'Project'), ('presentation', 'Presentation')], max_length=32)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('weight_percentage', models.PositiveIntegerField(default=0)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('manual_priority', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('missed', 'Missed'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('calculated_priority_score', models.FloatField(default=0)),
                ('is_locked_after_completion', models.BooleanField(default=False)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'due_time', 'created_at'],
            },
        ),
    ]
