# Generated by Django 5.2.7 on 2026-04-06 21:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMetricsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('week_start', models.DateField()),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('study_minutes_completed', models.PositiveIntegerField(default=0)),
                ('study_minutes_planned', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('overdue_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_metric_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
    ]
